version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: node app.js
          background: true
      - run:
          name: Run tests
          command: |
            sleep 1m
            npm test
            

workflows:
  sample:
    jobs:
      - build-and-test