version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    parallelism: 3
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run build
          command: node app.js
          background: true
      # - run:
      #     name: Run tests
      #     command: |
      #       sleep 1m
      #       npm test
      - run:
                name: Test application
                command: |
                    sleep 1m
                    TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
                    npm test
      - run:
          command: cp junit.xml ~/junit/
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
            

workflows:
  sample:
    jobs:
      - build-and-test